# Configure main menu and social menu
#[[main]]
#identifier = "projects"
#name = "Projects"
#url = "/projects"
#[main.params]
#icon = "hash"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/ax-i-om"

[social.params]
icon = "brand-github"

[[social]]
identifier = "email"
name = "Email"
url = "mailto:addressaxiom@pm.me"

[social.params]
icon = "messages"

